apiVersion: external-secrets.io/v1

kind: ExternalSecret

metadata:

  name: weather-db-secret

  namespace: backend


spec:

  refreshInterval: 1h


  secretStoreRef:

    name: aws-secrets-store

    kind: ClusterSecretStore


  target:

    name: weather-db-v4


  dataFrom:

  - extract:

      key: weather-db-v2
