apiVersion: v1
kind: ConfigMap
metadata:
  name: weatherapp-ui-config
  namespace: frontend
data:
  AUTH_HOST: "auth-service.backend.svc.cluster.local"
  AUTH_PORT: "8080"
  WEATHER_HOST: "weatherapp-weather.backend.svc.cluster.local"
  WEATHER_PORT: "5000"
