apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: backend

type: Opaque

stringData:
  DB_HOST: "app-db.cgnsgma4s270.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_USER: "admin"
  DB_PASSWORD: "StrongPassword123!"
  DB_NAME: "weather"
