

apiVersion: batch/v1
kind: Job

metadata:
  name: rds-init-job
  namespace: backend

spec:

  backoffLimit: 5

  template:

    spec:

      restartPolicy: Never

      containers:

      - name: mysql-client

        image: mysql:8.0


        env:

        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: DB_HOST


        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: DB_PORT


        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: DB_USER


        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: DB_PASSWORD


        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: DB_NAME


        command:
        - /bin/sh
        - -c


        args:
        - |

          echo "Connecting to RDS..."


          mysql \
          -h ${DB_HOST} \
          -P ${DB_PORT} \
          -u ${DB_USER} \
          -p${DB_PASSWORD} <<EOF


          CREATE DATABASE IF NOT EXISTS ${DB_NAME};


          USE ${DB_NAME};


          CREATE TABLE IF NOT EXISTS users (

              id INT AUTO_INCREMENT PRIMARY KEY,

              username VARCHAR(100) NOT NULL,

              password VARCHAR(255) NOT NULL

          );




          EOF


  
