apiVersion: external-secrets.io/v1

kind: ClusterSecretStore

metadata:
  name: aws-secrets-store

spec:

  provider:

    aws:

      service: SecretsManager

      region: us-east-1

      auth:

        jwt:

          serviceAccountRef:

            name: weather-app-sa

            namespace: backend
