name: Weather App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      CLUSTER_NAME: my-eks
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    ####################################
    # Docker Hub Login
    ####################################

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    ####################################
    # Setup Languages
    ####################################

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    ####################################
    # Build Docker Images
    ####################################

    - name: Build Auth Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/weather-auth:latest ./auth/

    - name: Build Weather Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/weather-api:latest ./weather/

    - name: Build UI Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/weather-ui:latest ./UI/

    ####################################
    # TESTS
    ####################################

    - name: Test Authentication (Go)
      working-directory: auth
      run: |
        go mod download
        go test ./...

    - name: Test Weather (Flask)
      working-directory: weather
      run: |
        pip install -r requirements.txt
        python -m compileall .

    - name: Test UI (Express)
      working-directory: UI
      run: |
        npm install
        npm test --if-present

    ####################################
    # Push Images
    ####################################

    - name: Push Auth Image
      run: |
        docker push $DOCKERHUB_USERNAME/weather-auth:latest

    - name: Push Weather Image
      run: |
        docker push $DOCKERHUB_USERNAME/weather-api:latest

    - name: Push UI Image
      run: |
        docker push $DOCKERHUB_USERNAME/weather-ui:latest

    ####################################
    # Configure AWS
    ####################################

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    ####################################
    # Update kubeconfig
    ####################################

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --name $CLUSTER_NAME \
          --region $AWS_REGION

    ####################################
    # Deploy
    ####################################

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/ui/
        kubectl apply -f kubernetes/authentication/
         kubectl apply -f kubernetes/weather/




